global:
  resolve_timeout: 5m
  smtp_smarthost: "__ALERTMANAGER_SMTP_SMARTHOST__"
  smtp_from: "__ALERTMANAGER_EMAIL_FROM__"
  smtp_auth_username: "__ALERTMANAGER_SMTP_AUTH_USERNAME__"
  smtp_auth_password: "__ALERTMANAGER_SMTP_AUTH_PASSWORD__"
  smtp_require_tls: __ALERTMANAGER_SMTP_REQUIRE_TLS__

route:
  receiver: "default-receiver"
  group_by:
    - "alertname"
    - "severity"
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - matchers:
        - severity="critical"
      receiver: "critical-notifier"
      continue: false

receivers:
  - name: "default-receiver"

  - name: "critical-notifier"
    slack_configs:
      - api_url: "__ALERTMANAGER_SLACK_WEBHOOK_URL__"
        channel: "__ALERTMANAGER_SLACK_CHANNEL__"
        username: "__ALERTMANAGER_SLACK_USERNAME__"
        send_resolved: true
        title: "[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}"
        text: |-
          Summary: {{ .CommonAnnotations.summary }}
          Severity: {{ .CommonLabels.severity }}
          Description: {{ .CommonAnnotations.description }}

    email_configs:
      - to: "__ALERTMANAGER_EMAIL_TO__"
        send_resolved: true
        headers:
          subject: "[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}"
